
#quarkus.mongodb.devservices.enabled = false
#quarkus.mongodb.connection-string = mongodb://localhost:27017
quarkus.mongodb.devservices.image-name=mongodb/mongodb-community-server:7.0.3-ubi8
quarkus.mongodb.drop-database-on-startup=true
quarkus.mongodb.database=hexa-archi-exercise

quarkus.http.auth.basic=true
quarkus.profile=dev

quarkus.log.console.format=%d{HH:mm:ss} %-5p traceId=%X{traceId}, parentId=%X{parentId}, spanId=%X{spanId}, sampled=%X{sampled} [%c{2.}] (%t) %s%e%n
quarkus.micrometer.export.prometheus.enabled=true
quarkus.micrometer.binder.http-client.enabled=true

# OpenAPI
quarkus.smallrye-openapi.info-title=Simple Todo API
%dev.quarkus.smallrye-openapi.info-title=Example API (dev)
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=Small and simple todo API